### create a user
POST https://api.acme.com/users
Content-Type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "test123"
}

### list users
GET https://api.acme.com/users


### acme web
GET https://www.acme.com/
