### create a user
POST http://api.acme.com/users
Content-Type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "test123"
}

### list users
GET http://api.acme.com/users
